const SALT_BYTE_SIZE = 10;
const HASH_ITERATIONS = 10000;
const HASH_KEY_LENGTH = 10;
const HASH_ALGORITHM = 'sha512';
const JWT_EXPIRATION_TIME = '1m';
const JWT_ISSUER = 'songa';

module.exports = {
    SALT_BYTE_SIZE,
    HASH_ITERATIONS,
    HASH_KEY_LENGTH,
    HASH_ALGORITHM,
    JWT_EXPIRATION_TIME,
    JWT_ISSUER,
};